version: '2'

services:

  bash:
    build:
      context: .
    image: ica:latest
    entrypoint: /bin/bash
    working_dir: /work
    volumes:
      - '.:/work:rw'

  test:
    build:
      context: .
    image: ica:latest
    command: bash -c 'nosetests -v -s'
    working_dir: /work
    volumes:
      - '.:/work:rw'
